# Generated by Django 5.2.17 on 2026-08-22 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notaventa',
            name='moneda',
            field=models.CharField(choices=[('BOB', 'Bolivianos'), ('USD', 'Dólares')], default='BOB', max_length=3),
        ),
        migrations.AddField(
            model_name='notaventa',
            name='tipo_cambio',
            field=models.DecimalField(decimal_places=4, default=6.96, max_digits=10),
        ),
    ]
