# Generated by Django 5.2.17 on 2026-08-21 21:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventario', '0001_initial'),
        ('productos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ingreso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('tipo', models.CharField(choices=[('COMPRA', 'Compra'), ('AJUSTE', 'Ajuste'), ('DEVOLUCION', 'Devolución')], max_length=15)),
                ('observacion', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='DetalleEgreso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=12)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='detalles_egreso', to='productos.producto')),
            ],
        ),
        migrations.CreateModel(
            name='DetalleIngreso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=12)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='detalles_ingreso', to='productos.producto')),
            ],
        ),
        migrations.CreateModel(
            name='Egreso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('tipo', models.CharField(choices=[('VENTA', 'Venta'), ('AJUSTE', 'Ajuste'), ('MERMA', 'Merma')], max_length=15)),
                ('observacion', models.TextField(blank=True)),
                ('almacen', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='egresos', to='inventario.almacen')),
            ],
        ),
    ]
