# Generated by Django 5.2.17 on 2026-08-21 21:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('compras', '0002_initial'),
        ('inventario', '0002_initial'),
        ('movimientos', '0001_initial'),
        ('ventas', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='egreso',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='egresos', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='egreso',
            name='venta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='egresos', to='ventas.notaventa'),
        ),
        migrations.AddField(
            model_name='detalleegreso',
            name='egreso',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='movimientos.egreso'),
        ),
        migrations.AddField(
            model_name='ingreso',
            name='almacen',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ingresos', to='inventario.almacen'),
        ),
        migrations.AddField(
            model_name='ingreso',
            name='compra',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ingresos', to='compras.compra'),
        ),
        migrations.AddField(
            model_name='ingreso',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ingresos', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='detalleingreso',
            name='ingreso',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='movimientos.ingreso'),
        ),
    ]
